# Generated by Django 6.0.4 on 2026-04-29 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='SCALE_01', max_length=50)),
                ('weight', models.FloatField(verbose_name='Cân nặng (kg)')),
                ('height', models.FloatField(verbose_name='Chiều cao (cm)')),
                ('temperature', models.FloatField(verbose_name='Nhiệt độ (°C)')),
                ('heart_rate', models.IntegerField(verbose_name='Nhịp tim (bpm)')),
                ('spo2', models.IntegerField(verbose_name='Nồng độ Oxy (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
